version: '3.7'
services:
  mongodb_container:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
    ports:
      - 8007:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: